modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/YukkuriC/HexOverpowered/issues"
license = "MIT"

[[mods]]
modId = "hexoverpowered"
version = "${version}"
displayName = "HexOverpowered"
authors = "YukkuriC"
description = '''
Various OP features for HexCasting and its addons
'''
logoFile = "logo.png"
updateJSONURL = "https://api.modrinth.com/updates/PkhtCPsD/forge_updates.json"
displayURL = "https://modrinth.com/project/hexoverpowered"

[[dependencies.hexoverpowered]]
modId = "minecraft"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexoverpowered]]
modId = "hexcasting"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexoverpowered]]
modId = "hexal"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexoverpowered]]
modId = "mekanism"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "hexop.mixins.json"
